
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-claim-tmax-io-v1alpha1-tfapplyclaim
  failurePolicy: Fail
  name: mutation.webhook.tfapplyclaim
  rules:
  - apiGroups:
    - claim.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - tfapplyclaims
  sideEffects: NoneOnDryRun

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-claim-tmax-io-v1alpha1-tfapplyclaim
  failurePolicy: Fail
  name: validation.webhook.tfapplyclaim
  rules:
  - apiGroups:
    - claim.tmax.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - tfapplyclaims
    - tfapplyclaims/status
  sideEffects: NoneOnDryRun
